### ISSUE TITLE
Example 4: UVIA calc is performed twice

### ISSUE THREAD

**Issue by mhord** [sparkfun/SparkFun_VEML6075_Arduino_Library#1]
Lines 75 and 77 both calculate uviaCalc. Is the second one supposed to be a '+=' operation or can the first operation be omitted?

**Comment by jimblom** [comment]
Good catch. This is a development artifact -- was beginning with calculating UVIA without the alpha/beta/delta/gamma "golden" constants. (They're defaulted to 1.0, so the calculation should end up the same.) Removed the second calculation in commit a091986.
