### ISSUE TITLE
VEML6075 EOL (end-of-life)

### ISSUE THREAD

**Issue by szerwi** [sparkfun/SparkFun_VEML6075_Arduino_Library#10]
As far as I know, VEML6075 is stated as end-of-life sensor since December 2019. Currently it is hard to get one on the online stores. Are there any alternatives for the VEML6075?

**Comment by santaimpersonator** [comment]
Currently, we do not have any options in our catalog. However, you can [sign up for our newsletter](https://www.sparkfun.com/Subscribe) to keep up with our latest product releases.

I am closing this issue since is doesn't have to do with the Arduino library.
