### ISSUE TITLE
ExampleZ: class VEML6075 has no member named 'uvcomp1' and 'uvcomp2'

### ISSUE THREAD

**Issue by LukaGitH** [sparkfun/SparkFun_VEML6075_Arduino_Library#7]
ExampleZ_VEML6075_UV_Test:17:27: error: 'class VEML6075' has no member named 'uvcomp1'
ExampleZ_VEML6075_UV_Test:17:57: error: 'class VEML6075' has no member named 'uvcomp2'

It won't compile because of that

**Comment by bboyho** [comment]
Hi,

I just saw your comment. I'm not sure what Arduino IDE version, library version, or board that you are using. It looks like the library was not installed correctly with your Arduino IDE?

Try re-installing the library with the Arduino library manager. Testing the *ExampleZ_VEEML6075_UV_Test.ino* out with Arduino IDE v1.8.9's library manager, I was able to compile with the **Arduino/Genuino Uno** board definition.
